<?php
/**
 * Defines a PHP class for the plugin (which inherits from the PmPlugin class)
 * to register the new plugin and define its methods to setup, install, activate, deactivate and uninstall the plugin.
 *
 */
G::LoadClass("plugin");

  define("PATH_PLUGIN_OS",PATH_CORE . "/plugins/odooStep/");
  set_include_path(
    PATH_PLUGIN_OS.PATH_SEPARATOR.
    get_include_path()
  );

  //Propel::init("/path/to/bookstore/build/conf/runtime-conf.php");
  // initialize Propel with converted config file
            //Propel::init( PATH_CORE . "config/databases.php" );

class odooStepPlugin extends PMPlugin
{
  
  
  public function odooStepPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "odooStep Plugin";
    $this->sDescription  = "Añade un paso para conectar con el XML-RPC de Odoo";
    $this->sPluginFolder = "odooStep";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

/**
 * Any code added to the setup() method in the pluginName.php file WILL BE EXECUTED EVERY TIME
 * ProcessMaker loads a web page, so do not add code which takes too long to execute or may cause errors.
 */
  public function setup() {
    //http://wiki.processmaker.com/3.0/Internal_Functions_and_Classes#PMPlugin::registerMenu.28.29
    $this->registerMenu("processmaker", "menuodooStep.php");
    //$this->registerMenu("processmaker", "menuConfigPage.php");

    /**
     * The first parameter of the registerStep() method is the external step's unique ID number,
     * which was automatically generated by ProcessMaker. The second parameter is the name of the file(s)
     * (without the extension) that will be executed when running the step. The third parameter 
     * is the name of the external step that is displayed to the user in ProcessMaker. Feel free to edit the external step's name.
     
     * Invalid value specified for `step_uid_obj`. Maximum 32 characters allowed. 4553885635943a689c55440011049885
     * Bad Request: Invalid value specified for `step_uid_obj`. Minimum 32 characters required.
     */
    for ($x = 0; $x < 10; $x++) {
      $this->registerStep($x."553885635943a689c55440011049885", "stepodooStepApplication", $x."odooStep step");
      //echo "The number is: $x <br>";
    } 

    //$this->registerStep("4553885635943a689c55440011049885", "stepodooStepApplication", "odooStep external step");
    $oHeadPublisher = &headPublisher::getSingleton();
    $oHeadPublisher->addExtJsScript("odooStep/dependencies/jquery-3.2.1.min", false); //Adding a javascript file .js
    $oHeadPublisher->addExtJsScript("odooStep/override", false); //Adding a javascript file .js

    //void headPublisher::addExtJsScript(string $filename, boolean $debug = false, boolean $isExternal = false)
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("odooStep", __FILE__);


